services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: # your password
      MYSQL_DATABASE: librarymanagement
    networks:
      - mynetwork

  web:
    build: .
    container_name: librarymanagement
    ports:
      - 8000:8000
    networks:
      - mynetwork
    command: ["/app/entrypoint.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    ports:
      - '5000:80'
      - '25:25'
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - mynetwork

  worker:
    build: .
    container_name: worker
    command: celery -A libmanagement worker --loglevel=info
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge